import { db } from "../../../firebase";
import {
  collection,
  query,
  getDocs,
  Timestamp,
  FirestoreDataConverter,
  QueryDocumentSnapshot,
  SnapshotOptions,
  DocumentData,
  orderBy,
  serverTimestamp,
  doc,
  getDoc,
  addDoc,
  updateDoc,
  deleteDoc,
} from "firebase/firestore";
import { Client } from "@/interfaces/clients"; // Adjust the import path as needed

// Client converter
const clientConverter: FirestoreDataConverter<Client> = {
  toFirestore(client: Client): DocumentData {
    // Since id is generated by Firestore, we omit it in the conversion to Firestore
    const { docId, ...data } = client;
    return {
      ...data,
      created_at: client.created_at || serverTimestamp(),
      updated_at: serverTimestamp(),
    };
  },
  fromFirestore(
    snapshot: QueryDocumentSnapshot<DocumentData>,
    options: SnapshotOptions
  ): Client {
    const data = snapshot.data(options);
    return {
      docId: snapshot.id,
      // stripeId: data.stripeId,
      status: data.status,
      // active: data.active,
      // deprecated: data.deprecated,
      // defaultRate: data.defaultRate,
      firstName: data.firstName,
      lastName: data.lastName,
      phoneNumber: data.phoneNumber,
      email: data.email,
      created_at: data.created_at,
      updated_at: data.updated_at,
    };
  },
};

// Reference to the user's clients collection
const clientsRef = (uid: string) =>
  collection(db, `users/${uid}/clients`).withConverter(clientConverter);

// Function to fetch clients
export async function fetchClients(uid: string): Promise<Client[]> {
  try {
    const q = query(clientsRef(uid), orderBy("created_at", "desc"));
    const querySnapshot = await getDocs(q);

    const clientsData = querySnapshot.docs.map((doc) => doc.data());
    return clientsData;
  } catch (error) {
    // console.error("Error fetching clients:", error);
    return [];
  }
}

// fetch a single booking type
export async function fetchClient(
  uid: string,
  id: string
): Promise<Client | undefined> {
  const clientRef = doc(clientsRef(uid), id);
  const clientSnapshot = await getDoc(clientRef);
  if (clientSnapshot.exists()) {
    return clientSnapshot.data();
  }
}

// Function to add a booking type to Firestore
export async function addClient(
  uid: string,
  client: Omit<Client, "docId"> // Exclude docId from the input type
): Promise<void> {
  const newClient = {
    ...client,
    created_at: serverTimestamp(),
    updated_at: serverTimestamp(),
  };
  await addDoc(clientsRef(uid), newClient);
}

// Function to update a client in Firestore
export async function updateClient(uid: string, client: Client): Promise<void> {
  const clientRef = doc(clientsRef(uid), client.docId);
  const updatedClient = {
    ...client,
    updated_at: serverTimestamp(),
  };
  await updateDoc(clientRef, updatedClient);
}

// Function to delete a client from Firestore
export async function deleteClient(uid: string, id: string): Promise<void> {
  const clientRef = doc(clientsRef(uid), id);
  await deleteDoc(clientRef);
}
